# Generated by Django 4.2.20 on 2025-04-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guestorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', help_text='Driver availability for auto-assignment', max_length=20),
        ),
    ]
